#!/usr/bin/env bash
# Configure a web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo /etc/init.d/nginx start
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
