#!/usr/bin/env bash
# Configure a web server
sudo apt-get update
sudo apt-get install nginx
sudo /etc/init.d/nginx start
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
