#!/usr/bin/env bash
# Task 0: Double the number of webservers
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "48a\ \tadd_header X-Served-By $hostname;\n" /etc/nginx/sites-available/default
sudo service nginx restart
