#!/usr/bin/env bash
# Task 0: Double the number of webservers
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "27i \add_header X-Served-By \$hostname always;" /etc/nginx/sites-available/default
sudo service nginx restart
