#!/usr/bin/env bash
# Task 1: Install your load balancer
sudo apt-get update
sudo apt-get install -y haproxy=1.6.\*
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo -e "\nfrontend haproxynode\n\tbind *:80\n\tmode http\n\tdefault_backend backendnodes\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "backend backendnodes\n\tbalance roundrobin\n\tserver 1478-web-01 34.75.231.107:80 check\n\tserver 1478-web-02 35.243.154.138:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
