#!/usr/bin/env bash
#Script that loops from 1 to 10
i=1
while [  $i -lt 21 ]; do
	case $i in
		4)
			echo -e "$i\nbad luck from China"
			;;
		9)
			echo -e "$i\nbad luck from Japan"
			;;
        	17)
                	echo -e "$i\nbad luck from Italy"
			;;
		*)
			echo $i
	esac
	((i++))
done
