#!/usr/bin/env bash
#Script that loops from 1 to 10
i=1
while [  $i -lt 21 ]; do
	if [ $i == 4 ]; then
		echo -e "$i\nbad luck from China"
	elif [ $i == 9 ]; then
		echo -e "$i\nbad luck from Japan"
        elif [ $i == 17 ]; then
                echo -e "$i\nbad luck from Italy"
	else
		echo $i
	fi
	((i++))
done
