#!/usr/bin/env bash
# Script that change the localhost
cp /etc/hosts /etc/copy_hosts
cat /etc/hosts > hosts.new
sed -i 's/127.0.0.1\s*localhost/127.0.0.2 localhost/' hosts.new
echo "8.8.8.8 facebook.com" >> hosts.new
mv -f hosts.new /etc/hosts
